### PR TITLE
Waitlist

### PR DESCRIPTION
**Pull request by Webnai**
this is the screen for the waitList page

### CODE REVIEW

**Comment by Webnai** [comment]
@mikehammond please I have built the screen for the wait list page

**Comment by mikehammond** [comment]
@Webnai run the cmd `npm run lint` on your end and resolve those linting errors and push it for me to review.

**Comment by Webnai** [comment]
well noted @mikehammond

**Comment by Webnai** [comment]
@mikehammond  we should be good on the lint errors now

**Pull request merged**
